<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>EntWatchSharp</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>warnings</Nullable>
    <Title>EntWatchSharp</Title>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
    <NoWarn>1701;1702</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>True</Optimize>
    <NoWarn>1701;1702</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.333" />
    <PackageReference Include="ZLinq" Version="1.4.12" />
    <PackageReference Include="ZString" Version="2.6.0" />
  </ItemGroup>
  <!-- Enable ZLinq.DropInGenerator -->
  <ItemGroup>
      <PackageReference Include="ZLinq.DropInGenerator" Version="1.4.12">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <AssemblyAttribute Include="ZLinq.ZLinqDropInAttribute">
          <_Parameter1></_Parameter1>
          <_Parameter2>ZLinq.DropInGenerateTypes.Everything</_Parameter2>
          <_Parameter2_IsLiteral>true</_Parameter2_IsLiteral>
          <_Parameter2_TypeName>ZLinq.DropInGenerateTypes</_Parameter2_TypeName>
      </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EntWatchSharpAPI\EntWatchSharpAPI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AnyBaseLib">
      <HintPath>API\AnyBaseLib.dll</HintPath>
    </Reference>
    <Reference Include="CS2-GameHUDAPI">
      <HintPath>API\CS2-GameHUDAPI.dll</HintPath>
    </Reference>
    <Reference Include="PlayerSettingsApi">
      <HintPath>API\PlayerSettingsApi.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="addons\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="copy /Y $(TargetDir)$(TargetName).dll $(TargetDir)addons\counterstrikesharp\plugins\EntWatchSharp\$(TargetName).dll" />
		<Exec Command="if not exist $(TargetDir)addons\counterstrikesharp\shared\EntWatchSharpAPI mkdir $(TargetDir)addons\counterstrikesharp\shared\EntWatchSharpAPI" />
		<Exec Command="copy /Y $(TargetDir)EntWatchSharpAPI.dll $(TargetDir)addons\counterstrikesharp\shared\EntWatchSharpAPI\EntWatchSharpAPI.dll" />
		<Exec Command="if exist $(SolutionDir)build rmdir /s/q $(SolutionDir)build" />
		<Exec Command="move /Y $(TargetDir)addons $(SolutionDir)build" />
	</Target>
  

</Project>
